### ISSUE TITLE
Error encountered when test your program

### ISSUE THREAD

**Issue by yuanjunchai** [sunreef/BlindSR#1]
There is an error happened when I test your blindSR with Set5 dataset:
Traceback (most recent call last):
  File "src/main.py", line 48, in <module>
    manager = Manager(arg_list)
  File "/media/sdc/yjchai/BlindSR/src/manager.py", line 32, in __init__
    self.launch_test()
  File "/media/sdc/yjchai/BlindSR/src/manager.py", line 483, in launch_test
    imageio.imwrite(output_file, highres_image)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py", line 255, in imwrite
    raise ValueError("Image must be a numpy array.")
ValueError: Image must be a numpy array.

**Comment by sunreef** [comment]
I do not have this issue on Ubuntu 18.04. Are you using a different OS ?

Can you try the latest commit ? I added an explicit conversion to NumPy arrays.

**Comment by yuanjunchai** [comment]
Yes! Problem solved.
But the first image is corrupted:
LR image 
![image](https://user-images.githubusercontent.com/25547974/75518161-3e1ed600-5a3b-11ea-801f-d48bf6d78964.png)
HR image
![image](https://user-images.githubusercontent.com/25547974/75518082-1596dc00-5a3b-11ea-8c9d-8c329325f1f9.png)
kernel
![image](https://user-images.githubusercontent.com/25547974/75518188-4a0a9800-5a3b-11ea-8e05-016a21ec7583.png)

Why does it happen?

**Comment by sunreef** [comment]
I have never seen that problem before.

Did you try to run the algorithm on the test image in the input folder ?

**Comment by yuanjunchai** [comment]
Yes, I tried to run it on 'input' and the result is great.
I have tried to run it on Set5 dataset and just this image is corrupt.

**Comment by sunreef** [comment]
I was able to reproduce the problem with the same input image.
It comes from the fact that the image has a larger height than width. I'm making assumptions somewhere in my code that the width is larger.

With the latest commit, it should work. I flip the image when loading it so that the width stays larger.

**Comment by yuanjunchai** [comment]
Great!
By the way, both generator and discriminator's loss are L1 loss, not adversarial loss?

**Comment by sunreef** [comment]
There is no adversarial loss in our algorithm. Only a simple L1 loss.
We call our networks generator and discriminator but they do not form a GAN. There is no competition between the two.
